### ISSUE TITLE
New Mediafire Download links don't work (e.g. https://www.mediafire.com/download/[id here])

### ISSUE THREAD

**Issue by fantastlcok** [TheAlienDrew/mediafire-direct-dl#1]
It seems that something has been updated, and the demo no longer works.

**Comment by Andrew-J-Larson** [comment]
@fantastlcok thanks for bringing this to my attention, it appears that mediafire is using a slightly different URL now when sharing download links. I'll get this fixed soon.

**Comment by Andrew-J-Larson** [comment]
Now it should be fixed.
